ERROR Invalid HTTP_HOST header: 'localhost'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/sites/envSites/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/sites/envSites/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost'. You may need to add 'localhost' to ALLOWED_HOSTS.
WARNING Bad Request: /toolbox/
ERROR Internal Server Error: /toolbox/admin/prosopographic/lugar/
Traceback (most recent call last):
  File "/home/sites/envSites/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/contrib/admin/options.py", line 714, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 240, in inner
    return view(request, *args, **kwargs)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/contrib/admin/options.py", line 2014, in changelist_view
    response = self.response_action(
  File "/home/sites/envSites/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1648, in response_action
    response = func(self, request, queryset)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/contrib/admin/actions.py", line 39, in delete_selected
    ) = modeladmin.get_deleted_objects(queryset, request)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/contrib/admin/options.py", line 2156, in get_deleted_objects
    return get_deleted_objects(objs, request, self.admin_site)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 171, in get_deleted_objects
    to_delete = collector.nested(format_callback)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 238, in nested
    roots.extend(self._nested(root, seen, format_callback))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 222, in _nested
    children.extend(self._nested(child, seen, format_callback))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 222, in _nested
    children.extend(self._nested(child, seen, format_callback))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 224, in _nested
    ret = [format_callback(obj)]
  File "/home/sites/envSites/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 144, in format_callback
    no_edit_link = "%s: %s" % (capfirst(opts.verbose_name), obj)
  File "/home/sites/toolbox/prosopographic/models.py", line 83, in __str__
    return f"{self.left_person} {self.get_relationship_type_display()} {self.right_person}"
AttributeError: 'Relationship' object has no attribute 'get_relationship_type_display'
ERROR Internal Server Error: /toolbox/admin/prosopographic/documento/
Traceback (most recent call last):
  File "/home/sites/envSites/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/response.py", line 74, in resolve_template
    return get_template(template, using=self.using)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: admin/import_export/change_list_import_export.html
ERROR Internal Server Error: /toolbox/admin/prosopographic/archivo/
Traceback (most recent call last):
  File "/home/sites/envSites/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/sites/envSites/lib/python3.10/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/sites/envSites/lib/python3.10/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/sites/envSites/lib/python3.10/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'toolbox_db.prosopographic_archivo' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sites/envSites/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/contrib/admin/options.py", line 714, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 240, in inner
    return view(request, *args, **kwargs)
  File "/home/sites/envSites/lib/python3.10/site-packages/import_export/admin.py", line 667, in changelist_view
    return super().changelist_view(request, extra_context)
  File "/home/sites/envSites/lib/python3.10/site-packages/import_export/admin.py", line 872, in changelist_view
    return super().changelist_view(request, extra_context)
  File "/home/sites/envSites/lib/python3.10/site-packages/import_export/admin.py", line 69, in changelist_view
    return super().changelist_view(request, extra_context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1981, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/contrib/admin/options.py", line 862, in get_changelist_instance
    return ChangeList(
  File "/home/sites/envSites/lib/python3.10/site-packages/django/contrib/admin/views/main.py", line 145, in __init__
    self.get_results(request)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/contrib/admin/views/main.py", line 312, in get_results
    result_count = paginator.count
  File "/home/sites/envSites/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/core/paginator.py", line 110, in count
    return c()
  File "/home/sites/envSites/lib/python3.10/site-packages/django/db/models/query.py", line 618, in count
    return self.query.get_count(using=self.db)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/db/models/sql/query.py", line 616, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
  File "/home/sites/envSites/lib/python3.10/site-packages/django/db/models/sql/query.py", line 602, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/home/sites/envSites/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/sites/envSites/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/sites/envSites/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/sites/envSites/lib/python3.10/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/sites/envSites/lib/python3.10/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/sites/envSites/lib/python3.10/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'toolbox_db.prosopographic_archivo' doesn't exist")
ERROR The number of GET/POST parameters exceeded settings.DATA_UPLOAD_MAX_NUMBER_FIELDS.
Traceback (most recent call last):
  File "/home/sites/envSites/lib/python3.10/site-packages/django/http/request.py", line 519, in __init__
    for key, value in parse_qsl(query_string, **parse_qsl_kwargs):
  File "/usr/lib/python3.10/urllib/parse.py", line 766, in parse_qsl
    raise ValueError('Max number of fields exceeded')
ValueError: Max number of fields exceeded

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sites/envSites/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = middleware_method(
  File "/home/sites/envSites/lib/python3.10/site-packages/django/middleware/csrf.py", line 464, in process_view
    self._check_token(request)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/middleware/csrf.py", line 367, in _check_token
    request_csrf_token = request.POST.get("csrfmiddlewaretoken", "")
  File "/home/sites/envSites/lib/python3.10/site-packages/django/core/handlers/wsgi.py", line 93, in _get_post
    self._load_post_and_files()
  File "/home/sites/envSites/lib/python3.10/site-packages/django/http/request.py", line 389, in _load_post_and_files
    self._post = QueryDict(self.body, encoding="utf-8")
  File "/home/sites/envSites/lib/python3.10/site-packages/django/http/request.py", line 526, in __init__
    raise TooManyFieldsSent(
django.core.exceptions.TooManyFieldsSent: The number of GET/POST parameters exceeded settings.DATA_UPLOAD_MAX_NUMBER_FIELDS.
WARNING Bad Request: /toolbox/admin/prosopographic/documento/
ERROR Internal Server Error: /toolbox/admin/esclavizados/lugar/
Traceback (most recent call last):
  File "/home/sites/envSites/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "/home/sites/envSites/lib/python3.10/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/sites/envSites/lib/python3.10/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/sites/envSites/lib/python3.10/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'toolbox_db.esclavizados_lugar' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sites/envSites/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/contrib/admin/options.py", line 715, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 240, in inner
    return view(request, *args, **kwargs)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1984, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/contrib/admin/options.py", line 863, in get_changelist_instance
    return ChangeList(
  File "/home/sites/envSites/lib/python3.10/site-packages/django/contrib/admin/views/main.py", line 145, in __init__
    self.get_results(request)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/contrib/admin/views/main.py", line 312, in get_results
    result_count = paginator.count
  File "/home/sites/envSites/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/core/paginator.py", line 110, in count
    return c()
  File "/home/sites/envSites/lib/python3.10/site-packages/django/db/models/query.py", line 620, in count
    return self.query.get_count(using=self.db)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/db/models/sql/query.py", line 629, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
  File "/home/sites/envSites/lib/python3.10/site-packages/django/db/models/sql/query.py", line 615, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/home/sites/envSites/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/sites/envSites/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/sites/envSites/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "/home/sites/envSites/lib/python3.10/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/sites/envSites/lib/python3.10/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/sites/envSites/lib/python3.10/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'toolbox_db.esclavizados_lugar' doesn't exist")
ERROR Internal Server Error: /toolbox/Browse/documentos
Traceback (most recent call last):
  File "/home/sites/envSites/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'documento-detail' not found. 'documento-detail' is not a valid view function or pattern name.
ERROR Internal Server Error: /toolbox/Detail/documento/1/
Traceback (most recent call last):
  File "/home/sites/envSites/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'documento-browse' not found. 'documento-browse' is not a valid view function or pattern name.
ERROR Internal Server Error: /toolbox/Browse/personas
Traceback (most recent call last):
  File "/home/sites/envSites/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/views/generic/list.py", line 154, in get
    self.object_list = self.get_queryset()
  File "/home/sites/toolbox/prosopographic/views.py", line 261, in get_queryset
    queryset = queryset.filter(
  File "/home/sites/envSites/lib/python3.10/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/sites/envSites/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1472, in build_filter
    return self._add_q(
  File "/home/sites/envSites/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/sites/envSites/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1383, in build_lookup
    lhs = self.try_transform(lhs, lookup_name)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1427, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'icontains' for ForeignKey or join on the field not permitted.
ERROR Internal Server Error: /toolbox/Browse/personas
Traceback (most recent call last):
  File "/home/sites/envSites/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'personas-browse' not found. 'personas-browse' is not a valid view function or pattern name.
ERROR Internal Server Error: /toolbox/Browse/personas
Traceback (most recent call last):
  File "/home/sites/envSites/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'personas-browse' not found. 'personas-browse' is not a valid view function or pattern name.
ERROR Internal Server Error: /toolbox/Browse/lugares
Traceback (most recent call last):
  File "/home/sites/envSites/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'lugar-browse' not found. 'lugar-browse' is not a valid view function or pattern name.
WARNING Not Found: /toolbox/Add/lugar/
WARNING Not Found: /toolbox/Add/lugar/
WARNING Not Found: /toolbox/Add/lugar/
WARNING Not Found: /toolbox/Browse/bautismos
WARNING Not Found: /toolbox/enslaved/
ERROR Internal Server Error: /toolbox/enslaved/
Traceback (most recent call last):
  File "/home/sites/envSites/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sites/toolbox/esclavizados/views.py", line 26, in home
    return render(request, 'dbgestor/home.html')
  File "/home/sites/envSites/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: dbgestor/home.html
WARNING Not Found: /toolbox/
ERROR Internal Server Error: /toolbox/prosopographic/
Traceback (most recent call last):
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/smartif.py", line 180, in translate_token
    op = OPERATORS[token]
KeyError: '{{'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sites/envSites/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sites/toolbox/prosopographic/views.py", line 20, in home
    return render(request, 'prosopographic/home.html')
  File "/home/sites/envSites/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/defaulttags.py", line 960, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/defaulttags.py", line 893, in __init__
    super().__init__(*args, **kwargs)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/smartif.py", line 171, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/smartif.py", line 182, in translate_token
    return self.create_var(token)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/defaulttags.py", line 896, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 597, in compile_filter
    return FilterExpression(token, self)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 698, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '{{' from '{{'
WARNING Not Found: /toolbox/Form/new/lugar/
ERROR Internal Server Error: /toolbox/
Traceback (most recent call last):
  File "/home/sites/envSites/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sites/toolbox/dashboard/views.py", line 5, in home
    return render(request, 'dashboard/home.html')
  File "/home/sites/envSites/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/defaulttags.py", line 961, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 515, in parse
    self.unclosed_block_tag(parse_until)
  File "/home/sites/envSites/lib/python3.10/site-packages/django/template/base.py", line 578, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 46: 'if'. Looking for one of: elif, else, endif.
WARNING Not Found: /toolbox/prosopographic/
WARNING Session data corrupted
WARNING Session data corrupted
WARNING Session data corrupted
WARNING Session data corrupted
